#' Add p-value annotations within facets
#'
#' Add significance labels and brackets for comparisons within each facet.
#'
#' @param plot_data A data frame used for plotting. Objects coercible to
#'   `data.frame` are also accepted.
#' @param stat_data A data frame containing statistical comparison results.
#'   This is typically the `@stat` slot extracted from the S4 result returned
#'   by [tinystatr::stat3()].
#' @param x A character string giving the x variable name in `plot_data`.
#' @param y A character string giving the y variable name in `plot_data`.
#' @param facet_var A character string giving the facet variable name.
#' @param label A character string giving the column name in `stat_data`
#'   used for significance labels.
#' @param hide.ns Logical; whether to hide rows with `"ns"` labels.
#' @param expand Numeric; vertical expansion above the data maximum.
#' @param step.increase Numeric; incremental step between annotation layers.
#' @param size Numeric; text size of significance labels.
#' @param bracket.size Numeric; line width of brackets.
#' @param tip.length Numeric; tip length passed to
#'   [ggpubr::stat_pvalue_manual()].
#' @param ... Additional arguments passed to [ggpubr::stat_pvalue_manual()].
#' @param x_levels Optional character vector specifying x-axis order.
#'
#' @return A ggplot layer generated by [ggpubr::stat_pvalue_manual()],
#'   or `NULL` if no valid comparisons remain.
#'
#' @export
add_pvalue_facet_annotation <- function(plot_data,
                                        stat_data,
                                        x,
                                        y,
                                        facet_var,
                                        label = "p.adj.signif",
                                        hide.ns = TRUE,
                                        expand = 0.12,
                                        step.increase = 0.10,
                                        size = 8,
                                        bracket.size = 1,
                                        tip.length = 0,
                                        ...,
                                        x_levels = NULL) {

  plot_data <- .as_df(plot_data)
  stat_data <- .as_df(stat_data)

  .validate_single_string(x, "x")
  .validate_single_string(y, "y")
  .validate_single_string(facet_var, "facet_var")
  .validate_single_string(label, "label")
  .validate_logical_scalar(hide.ns, "hide.ns")

  if (!x %in% colnames(plot_data)) {
    stop("`x` is not a column in `plot_data`.", call. = FALSE)
  }
  if (!y %in% colnames(plot_data)) {
    stop("`y` is not a column in `plot_data`.", call. = FALSE)
  }
  if (!facet_var %in% colnames(plot_data)) {
    stop("`facet_var` is not a column in `plot_data`.", call. = FALSE)
  }
  if (!facet_var %in% colnames(stat_data)) {
    stop("`facet_var` is not a column in `stat_data`.", call. = FALSE)
  }

  required_cols <- c("group1", "group2", label)
  missing_cols <- setdiff(required_cols, colnames(stat_data))
  if (length(missing_cols) > 0) {
    stop(
      paste0(
        "`stat_data` is missing required column(s): ",
        paste(missing_cols, collapse = ", ")
      ),
      call. = FALSE
    )
  }

  if (nrow(stat_data) == 0) {
    return(NULL)
  }

  .warn_if_numeric_label(stat_data, label)

  if (!"y.position" %in% colnames(stat_data)) {
    stat_data <- .prepare_pvalue_facet_annotation_data(
      plot_data = plot_data,
      stat_data = stat_data,
      x = x,
      y = y,
      facet_var = facet_var,
      label = label,
      hide.ns = hide.ns,
      expand = expand,
      step.increase = step.increase,
      x_levels = x_levels
    )
  } else {
    stat_data <- .filter_ns_rows(stat_data, label, hide.ns)
  }

  if (nrow(stat_data) == 0) {
    return(NULL)
  }

  ggpubr::stat_pvalue_manual(
    stat_data,
    label = label,
    y.position = "y.position",
    size = size,
    bracket.size = bracket.size,
    tip.length = tip.length,
    ...
  )
}
