#' Add p-value annotations to a non-faceted ggplot
#'
#' Add significance brackets and labels to a single-panel `ggplot2` object.
#' Bracket y-positions are computed automatically from the data, so no manual
#' `y.position` column is required in `stat_data`.
#'
#' `stat_data` is typically the `@stat` slot extracted from the S4 object
#' returned by [tinystatr::stat3()] or [tinystatr::stat2()].
#'
#' @param plot_data A data frame (or object coercible to one) containing the
#'   raw data used for plotting. Must include the columns named by `x` and `y`.
#' @param stat_data A data frame (or object coercible to one) containing
#'   pairwise comparison results. Must contain columns `group1`, `group2`, and
#'   the column specified by `label`. Typically the `@stat` slot from
#'   [tinystatr::stat3()] or [tinystatr::stat2()].
#' @param x A single character string giving the name of the discrete grouping
#'   variable (x-axis) in `plot_data`.
#' @param y A single character string giving the name of the numeric response
#'   variable (y-axis) in `plot_data`.
#' @param label A single character string giving the name of the column in
#'   `stat_data` that contains significance labels (e.g. `"*"`, `"**"`,
#'   `"ns"`). Defaults to `"p.adj.signif"`.
#' @param hide.ns Controls removal of non-significant rows before bracket
#'   positions are computed. Removing non-significant rows before computing
#'   positions prevents large empty gaps in the y-axis. Accepted values:
#'   \itemize{
#'     \item `FALSE` (default): keep all rows.
#'     \item `TRUE`: auto-detect a suitable significance column and remove rows
#'       labelled `"ns"` or rows with numeric values above `signif.cutoff`.
#'     \item `"p"`: filter using a p-value column.
#'     \item `"p.adj"`: filter using an adjusted p-value column.
#'     \item Any other character string: treated as the name of the column to
#'       use for filtering.
#'   }
#' @param signif.cutoff A single non-negative finite numeric value giving the
#'   threshold used when filtering numeric significance columns via `hide.ns`.
#'   Defaults to `0.05`.
#' @param expand A single non-negative numeric value controlling the gap between
#'   the top of the data and the first bracket, expressed as a fraction of the
#'   y-axis range. Defaults to `0.12`.
#' @param step.increase A single non-negative numeric value controlling the
#'   vertical distance between successive brackets, expressed as a fraction of
#'   the y-axis range. Defaults to `0.08`.
#' @param size Font size for significance labels, passed to
#'   [ggpubr::stat_pvalue_manual()]. Defaults to `6`.
#' @param bracket.size Line width of the significance brackets. Defaults to `1`.
#' @param tip.length Length of the bracket tips. Defaults to `0`.
#' @param ... Additional arguments passed to [ggpubr::stat_pvalue_manual()],
#'   such as `fontface = "bold"`.
#' @param x_levels An optional character vector explicitly specifying the order
#'   of groups on the x-axis. When `NULL` (default), the order is inferred from
#'   `plot_data[[x]]`: factor levels are used when available, otherwise groups
#'   are sorted alphabetically.
#'
#' @return A ggplot2 layer generated by [ggpubr::stat_pvalue_manual()], or
#'   `NULL` if no valid comparisons remain after filtering.
#'
#' @details
#' Bracket y-positions are computed by an internal helper that sorts comparisons
#' by span (number of groups spanned) and stacks brackets upward with a minimum
#' step of `step.increase * y_range`. Non-significant rows are removed
#' **before** position computation to avoid empty vertical gaps.
#'
#' @examples
#' \dontrun{
#' library(ggplot2)
#' library(tinystatr)
#' library(tinysignifr)
#'
#' data("ToothGrowth")
#' ToothGrowth$dose <- factor(ToothGrowth$dose)
#'
#' stat_result <- stat3(
#'   data = ToothGrowth,
#'   group = "dose",
#'   value = "len",
#'   formula = len ~ dose
#' )
#'
#' ggplot(ToothGrowth, aes(x = dose, y = len)) +
#'   geom_boxplot(aes(color = dose), fill = NA) +
#'   theme_classic() +
#'   theme(legend.position = "none") +
#'   add_pvalue_annotation(
#'     plot_data = ToothGrowth,
#'     stat_data = stat_result@stat,
#'     x = "dose",
#'     y = "len",
#'     hide.ns = TRUE
#'   )
#' }
#'
#' @seealso [add_pvalue_mixed()], [add_pvalue_facet_annotation()],
#'   [add_cross_facet_annotation()], [ggpubr::stat_pvalue_manual()]
#'
#' @export
add_pvalue_annotation <- function(plot_data,
                                  stat_data,
                                  x,
                                  y,
                                  label = "p.adj.signif",
                                  hide.ns = FALSE,
                                  signif.cutoff = 0.05,
                                  expand = 0.12,
                                  step.increase = 0.08,
                                  size = 6,
                                  bracket.size = 1,
                                  tip.length = 0,
                                  ...,
                                  x_levels = NULL) {

  plot_data <- .as_df(plot_data)
  stat_data <- .as_df(stat_data)

  .validate_single_string(x, "x")
  .validate_single_string(y, "y")
  .validate_single_string(label, "label")

  if (!is.logical(hide.ns) && !is.character(hide.ns)) {
    stop("`hide.ns` must be TRUE/FALSE or a character column specifier.", call. = FALSE)
  }

  if (!is.numeric(signif.cutoff) || length(signif.cutoff) != 1 ||
      is.na(signif.cutoff) || !is.finite(signif.cutoff) || signif.cutoff < 0) {
    stop("`signif.cutoff` must be one non-negative finite numeric value.", call. = FALSE)
  }

  if (!x %in% colnames(plot_data)) {
    stop("`x` is not a column in `plot_data`.", call. = FALSE)
  }
  if (!y %in% colnames(plot_data)) {
    stop("`y` is not a column in `plot_data`.", call. = FALSE)
  }

  required_cols <- c("group1", "group2", label)
  missing_cols <- setdiff(required_cols, colnames(stat_data))
  if (length(missing_cols) > 0) {
    stop(
      paste0(
        "`stat_data` is missing required column(s): ",
        paste(missing_cols, collapse = ", ")
      ),
      call. = FALSE
    )
  }

  if (nrow(stat_data) == 0) {
    return(NULL)
  }

  .warn_if_numeric_label(stat_data, label)
  stat_data <- .filter_ns_rows(
    stat_data = stat_data,
    label = label,
    hide.ns = hide.ns,
    signif.cutoff = signif.cutoff
  )

  if (nrow(stat_data) == 0) {
    return(NULL)
  }

  stat_data <- .compute_pvalue_positions(
    plot_data = plot_data,
    stat_data = stat_data,
    x = x,
    y = y,
    expand = expand,
    step.increase = step.increase,
    x_levels = x_levels
  )

  if (nrow(stat_data) == 0) {
    return(NULL)
  }

  ggpubr::stat_pvalue_manual(
    stat_data,
    label = label,
    y.position = "y.position",
    size = size,
    bracket.size = bracket.size,
    tip.length = tip.length,
    hide.ns = hide.ns,
    ...
  )
}
