#' Add p-value annotations within facets
#'
#' Add significance brackets for pairwise comparisons **within** each facet
#' panel of a faceted `ggplot2` figure. Bracket y-positions are computed
#' independently per facet so that brackets in one panel do not affect the
#' positions used in another.
#'
#' This function is typically paired with [add_cross_facet_annotation()] when
#' both within-facet and cross-facet annotations are needed.
#'
#' @param plot_data A data frame (or object coercible to one) used for plotting.
#'   Must include the columns named by `x`, `y`, and `facet_var`.
#' @param stat_data A data frame (or object coercible to one) containing
#'   pairwise comparison results. Must contain columns `group1`, `group2`, the
#'   column specified by `label`, and a column named by `facet_var` indicating
#'   which facet each comparison belongs to. Typically constructed by combining
#'   multiple `@stat` slots from [tinystatr::stat3()], one per facet level, with
#'   a `facet_var` column added via `mutate()`.
#' @param x A single character string giving the name of the discrete grouping
#'   variable (x-axis) in `plot_data`.
#' @param y A single character string giving the name of the numeric response
#'   variable (y-axis) in `plot_data`.
#' @param facet_var A single character string giving the name of the facet
#'   variable. Must be present in both `plot_data` and `stat_data`, and must
#'   match the variable used in `facet_wrap()`.
#' @param label A single character string giving the name of the significance
#'   label column in `stat_data`. Defaults to `"p.adj.signif"`.
#' @param hide.ns Controls removal of non-significant rows before bracket
#'   positions are computed. Defaults to `TRUE`. See
#'   [add_pvalue_annotation()] for accepted values.
#' @param signif.cutoff Numeric threshold used when filtering numeric
#'   significance columns via `hide.ns`. Defaults to `0.05`.
#' @param expand Vertical gap above the data maximum to the first bracket
#'   (fraction of y range). Defaults to `0.12`.
#' @param step.increase Vertical step between successive brackets within a facet
#'   (fraction of y range). Defaults to `0.10`.
#' @param size Font size for significance labels. Defaults to `8`.
#' @param bracket.size Line width of the brackets. Defaults to `1`.
#' @param tip.length Length of the bracket tips. Defaults to `0`.
#' @param ... Additional arguments passed to [ggpubr::stat_pvalue_manual()].
#' @param x_levels An optional character vector specifying the order of groups
#'   on the x-axis. When `NULL` (default), inferred from `plot_data[[x]]`.
#'
#' @return A ggplot2 layer generated by [ggpubr::stat_pvalue_manual()], or
#'   `NULL` if no valid comparisons remain after filtering.
#'
#' @details
#' If `stat_data` already contains a `y.position` column, automatic position
#' computation is skipped and the existing positions are used directly (after
#' filtering with `hide.ns`). Otherwise, positions are computed automatically
#' per facet.
#'
#' When used together with [add_cross_facet_annotation()], this function should
#' generally be added first so that the cross-facet layer can place its lines
#' above the within-facet brackets.
#'
#' @examples
#' \dontrun{
#' data("ToothGrowth")
#' ToothGrowth$dose <- factor(ToothGrowth$dose, levels = c("0.5", "1", "2"))
#' ToothGrowth$supp <- factor(ToothGrowth$supp, levels = c("OJ", "VC"))
#'
#' # ── Within-facet: compare dose levels within each supp group ──────
#' # Use variable/id to filter within stat3()
#' stat_oj <- stat3(
#'   data     = ToothGrowth,
#'   group    = "dose",
#'   value    = "len",
#'   variable = "supp",
#'   id       = "OJ",
#'   formula  = len ~ dose
#' )
#'
#' stat_vc <- stat3(
#'   data     = ToothGrowth,
#'   group    = "dose",
#'   value    = "len",
#'   variable = "supp",
#'   id       = "VC",
#'   formula  = len ~ dose
#' )
#'
#' # Combine: add the facet column so tinysignifr knows which panel each row belongs to
#' stat_within <- rbind(
#'   stat_oj@stat %>% mutate(supp = "OJ"),
#'   stat_vc@stat %>% mutate(supp = "VC")
#' )
#'
#' my_palette <- c("0.5" = "#56B4E9", "1" = "#009E73", "2" = "#E69F00")
#'
#' ggplot(ToothGrowth, aes(x = dose, y = len)) +
#'   geom_violin(aes(color = dose), fill = NA, linewidth = 1, width = 0.8) +
#'   geom_jitter(aes(color = dose), alpha = 0.5,
#'               width = 0.15, size = 2, height = 0,
#'               show.legend = FALSE) +
#'   stat_summary(geom = "errorbar", fun.data = "mean_se",
#'                color = "black", width = 0.2, linewidth = 1) +
#'   stat_summary(fun = "mean", geom = "point",
#'                color = "black", size = 2) +
#'   facet_wrap(~ supp, strip.position = "bottom") +
#'   scale_color_manual(values = my_palette) +
#'   scale_x_discrete(expand = expansion(add = 0.7)) +
#'   scale_y_continuous(expand = expansion(mult = c(0.05, 0.05))) +
#'   labs(x = "", y = "Tooth length", title = "OJ vs VC by dose") +
#'   theme_classic(base_size = 14) +
#'   theme(
#'     legend.position  = "none",
#'     strip.placement  = "outside",
#'     strip.background = element_rect(color = NA),
#'     strip.text       = element_text(size = 14, face = "bold")
#'   ) +
#'   add_pvalue_facet_annotation(
#'     plot_data     = ToothGrowth,
#'     stat_data     = stat_within,    # combined @stat with supp column
#'     x             = "dose",
#'     y             = "len",
#'     facet_var     = "supp",         # must match facet_wrap variable
#'     label         = "p.adj.signif",
#'     hide.ns       = TRUE,
#'     expand        = 0.12,
#'     step.increase = 0.10,
#'     size          = 6,
#'     bracket.size  = 1,
#'     tip.length    = 0,
#'     fontface      = "bold"
#'   )
#' }
#'
#' @seealso [add_pvalue_annotation()], [add_cross_facet_annotation()],
#'   [ggpubr::stat_pvalue_manual()]
#'
#' @export

add_pvalue_facet_annotation <- function(plot_data,
                                        stat_data,
                                        x,
                                        y,
                                        facet_var,
                                        label = "p.adj.signif",
                                        hide.ns = TRUE,
                                        signif.cutoff = 0.05,
                                        expand = 0.12,
                                        step.increase = 0.10,
                                        size = 8,
                                        bracket.size = 1,
                                        tip.length = 0,
                                        ...,
                                        x_levels = NULL) {

  plot_data <- .as_df(plot_data)
  stat_data <- .as_df(stat_data)

  .validate_single_string(x, "x")
  .validate_single_string(y, "y")
  .validate_single_string(facet_var, "facet_var")
  .validate_single_string(label, "label")

  if (!is.logical(hide.ns) && !is.character(hide.ns)) {
    stop("`hide.ns` must be TRUE/FALSE or a character column specifier.", call. = FALSE)
  }

  if (!is.numeric(signif.cutoff) || length(signif.cutoff) != 1 ||
      is.na(signif.cutoff) || !is.finite(signif.cutoff) || signif.cutoff < 0) {
    stop("`signif.cutoff` must be one non-negative finite numeric value.", call. = FALSE)
  }

  if (!x %in% colnames(plot_data)) {
    stop("`x` is not a column in `plot_data`.", call. = FALSE)
  }
  if (!y %in% colnames(plot_data)) {
    stop("`y` is not a column in `plot_data`.", call. = FALSE)
  }
  if (!facet_var %in% colnames(plot_data)) {
    stop("`facet_var` is not a column in `plot_data`.", call. = FALSE)
  }
  if (!facet_var %in% colnames(stat_data)) {
    stop("`facet_var` is not a column in `stat_data`.", call. = FALSE)
  }

  required_cols <- c("group1", "group2", label)
  missing_cols <- setdiff(required_cols, colnames(stat_data))
  if (length(missing_cols) > 0) {
    stop(
      paste0(
        "`stat_data` is missing required column(s): ",
        paste(missing_cols, collapse = ", ")
      ),
      call. = FALSE
    )
  }

  if (nrow(stat_data) == 0) {
    return(NULL)
  }

  .warn_if_numeric_label(stat_data, label)

  if (!"y.position" %in% colnames(stat_data)) {
    stat_data <- .prepare_pvalue_facet_annotation_data(
      plot_data     = plot_data,
      stat_data     = stat_data,
      x             = x,
      y             = y,
      facet_var     = facet_var,
      label         = label,
      hide.ns       = hide.ns,
      signif.cutoff = signif.cutoff,
      expand        = expand,
      step.increase = step.increase,
      x_levels      = x_levels
    )

  } else {
    stat_data <- .filter_ns_rows(
      stat_data = stat_data,
      label = label,
      hide.ns = hide.ns,
      signif.cutoff = signif.cutoff
    )
  }

  if (nrow(stat_data) == 0) {
    return(NULL)
  }

  ggpubr::stat_pvalue_manual(
    stat_data,
    label = label,
    y.position = "y.position",
    size = size,
    bracket.size = bracket.size,
    tip.length = tip.length,
    hide.ns = hide.ns,
    ...
  )
}
